# Generated by Django 3.0.6 on 2020-05-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vent_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacilityName', models.CharField(max_length=100)),
                ('Tier', models.IntegerField()),
                ('Region', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('lat', models.FloatField(verbose_name='Lat')),
                ('lng', models.FloatField(verbose_name='Long')),
                ('Total_Vents', models.IntegerField()),
                ('Available_Vents', models.IntegerField()),
                ('Predicted_Vent_Shortage_in_14days', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vent_Availability',
                'verbose_name_plural': 'Vent_Availabilities',
                'db_table': 'veny_availability',
            },
        ),
    ]
