# Generated by Django 3.0.6 on 2020-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vent_availability',
            name='Available_Vents',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vent_availability',
            name='Total_Vents',
            field=models.CharField(max_length=4),
        ),
    ]
