# Generated by Django 3.0.6 on 2020-05-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vents', '0004_auto_20200518_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vent_availability',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='vent_availability',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Long'),
        ),
    ]
